# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mentor Matching - Team 19
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew Bell, Christopher Lau and Harry Chen are working on creating a system
  to match mentors and mentees based on their preferences, on behalf of Atos UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile*
  - node_modules
  - package.json
  - bower.json
  - gulpfile.js
  - assets/bower_components
  - facebook-sync

github: https://github.com/mbellgb/syseng19-code
paginate: 5
